### ISSUE TITLE
Dependency Issue

### ISSUE THREAD

**Issue by programmer-ceds** [linuxmint/xviewer#102]
```
 * Xviewer version 2.6.0
 * Distribution - Mint 19.1 Cinnamon
```
@clefebvre 
Apologies if I am wrong and this is an issue of my own making. If I clone the xviewer master, run mint-build and then try to install xviewer_2.6.0_amd64.deb with GDebi it reports that xviewer depends on xapps-common >= 1.8.4 - this is ahead of the versions provided by Mint 18 and Mint 19. My current pull request (#101) fails for the same reason.

**Steps to reproduce**
As above

**Expected behaviour**
xviewer dependencies would allow it to run on Mint 18 and Mint19

**Comment by programmer-ceds** [comment]
I have just cloned xviewer then run mint-build and produced V2.6.2 - but GDebi Package Installer still refuses to install xviewer with the same error message as noted in my previous comment. How can Clement build it when I can't? Or is it a problem that I am using Cinnamon and he is using Mate?

**Comment by leigh123linux** [comment]
He is using xapps master

https://github.com/linuxmint/xviewer/blob/master/.circleci/config.yml#L16

Xviewer version 2.6.0 is Mint-20 and LMDE4 only
