### ISSUE TITLE
Support AVIF ?

### ISSUE THREAD

**Issue by svastian99** [linuxmint/xviewer#103]
Will xviewer plan to support avif image?. 
I suppose that since AV1 is an open source codec there is some possibility, right?

**Comment by haggen88** [comment]
Libavif would be useful in this case
https://github.com/AOMediaCodec/libavif

**Comment by haggen88** [comment]
[gThumb](https://gitlab.gnome.org/GNOME/gthumb/-/blob/master/README.md) uses [libheif](https://github.com/strukturag/libheif) to display AVIF/HEIF images
