### ISSUE TITLE
Cannot open files with wrong extension

### ISSUE THREAD

**Issue by JulianGro** [linuxmint/xviewer#104]
```
 * Xviewer version 2.4.3
 * Distribution - Linux Mint 19.3 Cinnamon
```

**Issue**
Xviewer is unable to open files that have a wrong file extension.
for example, when a JPEG file has a `.png` file extension, it will just show the error "Not a PNG file" rather than just opening it.

**Steps to reproduce**
- take a jpeg file
- change the file extension to png
- Xviewer will not open it anymore

**Expected behaviour**
Xviewer should see that it is a JPEG file and should just open it.

**Other information**
While the file extension *should* never be wrong, I have encountered a lot of JPEG files named PNG. I assume this might be people changing the file extension when saving a file and their application saving it as a different file type anyways.

**Comment by svastian99** [comment]
The same thing happens to me ... webp files files named jpg.

**Comment by programmer-ceds** [comment]
Following the merging of PR #123 this issue can be closed now.
