### ISSUE TITLE
New fealure in PNG

### ISSUE THREAD

**Issue by JeSuisEnPanne** [linuxmint/xviewer#105]
How are you today ?

Can you add an option in: Xviewer?
When I open a Transparent PNG file,
Is it possible to add any color to the background.
To visualize the probable result.

Thank you

**Comment by programmer-ceds** [comment]
This is already included (at least on V2.6.2 and I believe on much older versions).

"Edit/Preferences"
"Image View" tab
"Transparent Parts" section
Select "As custom colour:"
Choose the colour that you want.

If that's what you want you could then close the issue.

**Comment by JeSuisEnPanne** [comment]
how are you today?
yes it works in 2.4.3 Xviewer!
Thank you
