### ISSUE TITLE
[Feature request] Add WebP support

### ISSUE THREAD

**Issue by haggen88** [linuxmint/xviewer#107]
It would be very useful if xviewer could open webp files which is a format that has been widely used in Internet. Libraries like [libwebp](https://github.com/webmproject/libwebp) (used by [gThumb](https://gitlab.gnome.org/GNOME/gthumb)) or [imlib2-webp](https://github.com/gawen947/imlib2-webp) can be useful.

In case you have problems with [gdk-pixbuf](https://gitlab.gnome.org/GNOME/gdk-pixbuf/-/issues/103) , perhaps webp-pixbuf-loader could be useful:

https://github.com/aruiz/webp-pixbuf-loader/
https://github.com/NathanJPlummer/webp-pixbuf-loader

**Comment by Hordeking** [comment]
Agreed. I'm running into a lot of webp files these days, even if the url has a jpg or png in there, when I save as, it always comes back as a webp.

**Comment by haggen88** [comment]
Apparently we are not the only ones who think like this.  
#76 & #23

**Comment by cptX** [comment]
Please implement this soon. In another post this feature was requested 4 years ago!!

**Comment by amitbha** [comment]
Agreed. I'm using feh for webp.

**Comment by clefebvre** [comment]
Duplicate of https://github.com/linuxmint/xviewer/issues/23.
