### ISSUE TITLE
Xviever does not show entire image for very wide panoramas

### ISSUE THREAD

**Issue by zztob** [linuxmint/xviewer#118]
```
 * Xviewer version (xviewer --version): 2.6.2
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...): Linux Mint Cinnamon 20
```

**Issue**
While sorting my photos I came across several panoramas (very wide ones from Samsung S8) that xviewer would not show completely. The photo is cropped at the right hand side and shows a white area instead where still some parts of the image should be. See the screenshot below (Gimp on top, Xviewer below)

![xviewer_panorama_issue](https://user-images.githubusercontent.com/10603754/99836553-9320f000-2b66-11eb-9ef2-56418a57b88b.jpg)

**Steps to reproduce**
Simply open a very large (regarding pixel size) image. The issue is independent of window size (afaict) and zoom levels. I can provide example files if desired.

**Expected behaviour**
Display the entire image.

**Other information**
Other image viewers (eg gthumb) and programs (eg GIMP) are able to open the files and display them entirely. From the comparison of two photos where it happens I suspect that Xviewer cuts the content beyond 16384px width. Is this a built-in hard limit or can it be configured somewhere?

**Comment by mtwebster** [comment]
Can you link to an example image? Not that I doubt your result, it's just a policy that I test.

Thanks!

**Comment by zztob** [comment]
Here you go!

I had to reduce the quality quite substantially via GIMP to get below 10MB (export with JPEG quality 60%, original file size is 34MB). The issue persists with the new file, so it's independent of whatever GIMP does during the export.
Thanks for taking care of this :)

![big_panorama](https://user-images.githubusercontent.com/10603754/101361508-59a6ef00-389f-11eb-9476-93d34d8aaf86.jpg)

**Comment by programmer-ceds** [comment]
This issue can now be closed
