### ISSUE TITLE
"Vetical Pan" typo

### ISSUE THREAD

**Issue by muzena** [linuxmint/xviewer#120]
@clefebvre 
Vetical or Vertical?

data/xviewer-preferences-dialog.ui:                          <item id="1" translatable="yes">Vetical Pan</item>
data/xviewer-preferences-dialog.ui:                          <item id="1" translatable="yes">Vetical Pan</item>
data/xviewer-preferences-dialog.ui:                          <item id="1" translatable="yes">Vetical Pan</item>
data/xviewer-preferences-dialog.ui:                          <item id="1" translatable="yes">Vetical Pan</item>
data/xviewer-preferences-dialog.ui:                          <item id="1" translatable="yes">Vetical Pan</item>
data/xviewer-preferences-dialog.ui:                          <item id="1" translatable="yes">Vetical Pan</item>
data/xviewer-preferences-dialog.ui:                          <item id="1" translatable="yes">Vetical Pan</item>
data/xviewer-preferences-dialog.ui:                          <item id="1" translatable="yes">Vetical Pan</item>

**Comment by programmer-ceds** [comment]
My mistake. I'll fix it once I can get to a position where I can build the app again.

**Comment by programmer-ceds** [comment]
This issue appears to have been corrected as part of changes mode to the mouse scroll wheel option texts earlier today by Clement.

**Comment by programmer-ceds** [comment]
This issue can now be closed.
