### ISSUE TITLE
configure error: Package 'xapp', required by 'virtual:world', not found

### ISSUE THREAD

**Issue by dodona2** [linuxmint/xviewer#122]
```
 * Xviewer version (xviewer --version)
git pull
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Fedora 33
```

**Issue**
configure error
Package 'xapp', required by 'virtual:world', not found

**Steps to reproduce**
./configure

**Expected behaviour**
no error

**Other information**

**Comment by leigh123linux** [comment]
Try installing the build deps instead of filing non issues.

```
sudo dnf install xapps-devel
```
