### ISSUE TITLE
Xviewer is unable to read svgz files.

### ISSUE THREAD

**Issue by Hordeking** [linuxmint/xviewer#128]
```
 * Xviewer version 2.8.3
 * Mint 20.1
```
**Issue**
Xviewer is unable to read svgz files.
The issue occurs when producing svgz files using inkscape or by directly compressing a svg using gzip.
Uncompressed svg is confirmed to be viewable with no error using xviewer and other tools.

**Steps to reproduce**
Attempt to open svgz using xviewer. 
`Error: Could not load filename.svgz
Unrecognized image file format`

**Expected behaviour**
Expect svgz image file to be opened and identical to uncompressed svg image file

**Other information**
No other information available. No verbosity option is available to emit debugging information.

**Comment by Hordeking** [comment]
Addition: This is a regression. I installed xviewer 2.6.2 [from the official repository](http://packages.linuxmint.com/pool/backport/x/xviewer/xviewer_2.6.2%2bulyana_amd64.deb), and when I went to open the same file that 2.8.3 fails to open, it opened just fine.

**Comment by Hordeking** [comment]
This may come down to the mime type. Apparently xviewer is looking for something with mime type image/svg+xml-compressed, but when I run file --mime-type foo.svgz, it returns application/gzip (which is entirely reasonable, since it _is_ a gzipped svg file.
I'm under the impression that this particular check is new since 2.6.2. And since 2.6.2 is able to hatch the svgz file despite the mime type not being image/svg+xml-compressed, I'm going to go out on a limb and say that either xviewer needs to be tweaked a little (seems likely), or Mint needs to have the mime types upgraded (which seems unlikely)

**Comment by programmer-ceds** [comment]
Can you post a file that exhibits the problem please and I'll see if I can sort the problem.

**Comment by Hordeking** [comment]
Sure. I've included the raw svg as well, though you could just get that by gunzipping the svgz manually.

[foo.tar.gz](https://github.com/linuxmint/xviewer/files/5976310/foo.tar.gz)

**Comment by Hordeking** [comment]
Possble suggestion: Are there any other scenarios where a system mime type is likely to return something unexpected for a known file type? If so, perhaps we should just look for a class of the prime mime type (ie if the first part is application vs image) if the mime type isn't in the whitelist, and if there's a conflict, go with the mime type by extension if it IS in the whitelist since it's a better pick. Its basically just a slightly more general check.

**Comment by programmer-ceds** [comment]
Good idea. On the basis that xviewer won't (I assume) open any files with a mime type that starts "application/" I have changed the code to use the mime type based on extension if this starts with "image/" AND the mime type based on content starts with "application/". xviewer may still fail to open the file but at least it has been given a chance.

(Note that the mimetype command you referred to seems to operate solely on the basis of the file extension - give it a jpg with a png extension and it returns a mime type indicating that the file is a png - this is exactly the problem that xviewer had before PR #123)

**Comment by Hordeking** [comment]
Might still be wise to throw a warning in these cases. I've caught a fair
number of files that were valid images, but with incorrect extensions when
I tried to open them and it didn't like them.

**Comment by programmer-ceds** [comment]
Following the inclusion of PR #123 xviewer will open image files that have the wrong extension if they can be recognised based on the 'magic numbers' or on content. Such files are opened and displayed without a warning as per pix, GIMP and other programs.

Giving an svgz file an incorrect extension can't be handled and xviewer will display an error message if it tries to open such files. An svg file is recognised as such from its content and is opened successfully even if it has the extension relating to a different image file type. (Note that the mimetype command reports the file as being of the type indicated by the extension for both svg and svgz files that have the wrong extension).

**Comment by Hordeking** [comment]
I was actually thinking about situations where a png has a jpg extension and so on, you know, stuff with magic numbers that has a contradictory extension.

**Comment by programmer-ceds** [comment]
The master version of xviewer will open such files without a problem (although no warning is displayed). The type of file is determined based on magic numbers, content and finally from the extension (which is the least reliable of the three methods). The chances of a binary or zip file (for instance) containing the magic numbers is surely remote - but if this should happen then xviewer will probably give an error message to say that it can't open the file.

I'm not entirely sure why people have image files with the wrong extensions (am I missing the obvious?) but xviewer opens them anyway.

**Comment by Hordeking** [comment]
This is probably human error when naming the file. I've run into a few where the webserver insists on sending a webp file depending on which browser I'm using, even if the url itself is requesting a jpg. The first time I ran into this, I wasn't paying attention and named it jpeg and was quite confused until I attempted to ident the file manually and it came back as something besides a jpeg.
I've also typoed jpegs as png on occasion.
Probably not an especially critical check, but might be nice if it isn't much work to check.

**Comment by programmer-ceds** [comment]
OK, I'll consider submitting a change to add a warning message if an image file has the wrong extension once the two pull requests that I have active at the moment have been accepted or rejected. The warning would include a option to disable further warnings for that session (as per the Shift+Del dialog). At least at the moment xviewer will open image files with the wrong extension (svgz files excepted!)

**Comment by Hordeking** [comment]
Not sure if I should close the issue now or wait till the PR is accepted.

**Comment by JosephMcc** [comment]
I would wait until it's merged. If the PR uses something like `Fixes: https://github.com/linuxmint/xviewer/issues/128` in the commit message, it will be closed automatically.

**Comment by Hordeking** [comment]
Question for the repo admin, is this PR going to be merged anytime soon and packaged for the repository?

**Comment by rosecitytransit** [comment]
> The chances of a binary or zip file (for instance) containing the magic numbers is surely remote

If the file can be identified as being compressed (especially if a compression format that only supports single files, like gzip), wouldn't the proper course be to pass it to the decompression program/library, and then attempt to read the returned, uncompressed data stream? I know SVGZ may be a special case where there's a file type defined for the combination of file and compression (whereas most types you would have to do .svg.gz where the compression is separate).

**Comment by Hordeking** [comment]
That's an interesting thought. I don't know how many other formats are just gzipped versions of another one, at least in the image space.

**Comment by programmer-ceds** [comment]
I've just tried to extract the example svgz file that you supplied using the archive manager - this fails. I've also tried opening a zipped jpeg (a .zip file) using GIMP, a zipped pdf file with Document Viewer and a zipped odt file with LibreOffice Writer all give error messages and refuse to open the files. Adding the facility to open zipped image files would therefore seem to make xviewer unique (albeit based on a limited number of tests) and probably of little use - I can't say that I have ever thought of opening a zipped file with the application appropriate to the zipped file type.

I certainly don't think that this should be included in PR 129 which simply rectifies an error that was unintentionally introduced in PR 123.

**Comment by Hordeking** [comment]
> I've just tried to extract the example svgz file that you supplied using the archive manager - this fails.
foo.svgz opened in archive manager for me just fine.

**Comment by programmer-ceds** [comment]
> > I've just tried to extract the example svgz file that you supplied using the archive manager - this fails.
> 
> foo.svgz opened in archive manager for me just fine.

Archive Manager 3.38.0 on my system (Mint 20.1) opens foo.svgz in that it shows foo.svg - but if I then try "Open" or "Open With..."  I get ""An error occurred while extracting files." which is why I said it fails to open the file. (A red-herring really since the issue will go when PR #129 is merged)

**Comment by Hordeking** [comment]
On my system, svgz is associated with xviewer, so if I want to open it with archive manager, I _must_ "open with...". When I do it, I don't see any problems at all. Unless I misunderstand what issue you are having? Can you open archive manager first and then from AM open the svgz file? What happens if you rename it to svg.gz?

**Comment by programmer-ceds** [comment]
On my system svgz files are set to open with Inkscape.

If I right-click on foo.svgz and open it with the AM or if I open the AM and browse to foo.svgz it shows that the archive contains foo.svg. Right-clicking on foo.svg within AM shows no suggested programs for Open With...  Left-clicking on Open or Open With.. results in the error message noted in my previous post. Is this not an issue for AM rather than xviewer since xviewer will open svgz files once the PR is merged?

**Comment by programmer-ceds** [comment]
On my system svgz files are set to open with Inkscape.

If I right-click on foo.svgz and open it with the AM or if I open the AM and browse to foo.svgz it shows that the archive contains foo.svg. Right-clicking on foo.svg within AM shows no suggested programs for Open With...  Left-clicking on Open or Open With.. results in the error message noted in my previous post. Is this not an issue for AM rather than xviewer since xviewer will open svgz files once the PR is merged?

("7z e foo.svgz" extracts foo.svg and this can then be opened by xviewer)

**Comment by Hordeking** [comment]
I think archive manager has a different/independent file association set than the system set.

I think you're right that the issue you're seeing is there is an AM issue rather than an xviewer issue, wholly separate from PR #129
