### ISSUE TITLE
Thumbnails don't rotate

### ISSUE THREAD

**Issue by P-Woods** [linuxmint/xviewer#13]
When selected files are rotated and saved in a batch, the 2nd and subsequent thumbs are not rotated.
The main images and 1st thumb work fine, the subsequent thumbnails don't rotate.
You can see this happen in Thunar, where just 1 thumbnail rotates instantly.
Subsequent thumbs are refreshed (D-bus I guess) and (in my setup) black borders appear. 
It must be that Xviewer is replacing the thumb with a new version, BUT taken pre-rotate. 
This is what is saved to file. 
![orig0001](https://cloud.githubusercontent.com/assets/22316637/18665100/7ceb32b8-7f1d-11e6-969c-8114842d3178.jpg)
![orig0002](https://cloud.githubusercontent.com/assets/22316637/18665101/7cefbebe-7f1d-11e6-87fe-9e474d43ac7c.jpg)
![saved001](https://cloud.githubusercontent.com/assets/22316637/18665102/7cf80560-7f1d-11e6-81de-c3c569fa0658.jpg)
![saved002](https://cloud.githubusercontent.com/assets/22316637/18665103/7cf9876e-7f1d-11e6-82c9-8d53ed51e555.jpg)

This version (with borders) in displayed in image gallery strip.

**Comment by P-Woods** [comment]
P.S. xviewer is 1.0.6+sarah on Mint 18 64bit

**Comment by icarter09** [comment]
@P-Woods are you still experiencing this issue?

**Comment by P-Woods** [comment]
Sorry it's been a while. Waiting too long for a new distro.
I'm trying to get Mint 19.3 going, not easy!
xviewer 2.4.3+tricia is installed but not in the applications menu.
Performing the actions from above, i.e. rotate a batch and save:
the main images are all rotated and saved, but the thumbnails (as viewed in another viewer) are not updated at all. Subsequently, the thumbs displayed  in the image gallery become out of sync with the main image.
