### ISSUE TITLE
Launching xviewer results in lots of console errors.

### ISSUE THREAD

**Issue by poldon** [linuxmint/xviewer#141]
```
 * Xviewer version: Xviewer 2.8.3
 * Distribution - (Mint 20.1)
```

**Issue**

Every time I launch Xviewer, it results in lots of console errors.  Most of the time it launches fine, but others it segfaults until I reboot.

**Steps to reproduce**

Launch Xviewer from the shell.

**Expected behaviour**

No output on the shell.

**Other information**

Here are the errors:

** (xviewer:9568): WARNING **: 10:33:57.354: Couldn't load UI resource: The resource at “/org/x/viewer/plugins/exif-display/exif-display.ui” does not exist

(xviewer:9568): GLib-GObject-WARNING **: 10:33:57.354: invalid (NULL) pointer instance

(xviewer:9568): GLib-GObject-CRITICAL **: 10:33:57.354: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(xviewer:9568): XVIEWER-CRITICAL **: 10:33:57.354: xviewer_sidebar_add_page: assertion 'GTK_IS_WIDGET (main_widget)' failed

(xviewer:9568): Gtk-CRITICAL **: 10:33:57.354: gtk_widget_show_all: assertion 'GTK_IS_WIDGET (widget)' failed

(xviewer:9568): Gtk-CRITICAL **: 10:33:57.477: gtk_label_set_text: assertion 'GTK_IS_LABEL (label)' failed

(xviewer:9568): Gtk-CRITICAL **: 10:33:57.477: gtk_label_get_label: assertion 'GTK_IS_LABEL (label)' failed

(xviewer:9568): Gtk-CRITICAL **: 10:33:57.477: gtk_widget_set_tooltip_text: assertion 'GTK_IS_WIDGET (widget)' failed

(xviewer:9568): Gtk-CRITICAL **: 10:33:57.477: gtk_label_set_text: assertion 'GTK_IS_LABEL (label)' failed

(xviewer:9568): Gtk-CRITICAL **: 10:33:57.477: gtk_label_set_text: assertion 'GTK_IS_LABEL (label)' failed

(xviewer:9568): Gtk-CRITICAL **: 10:33:57.477: gtk_label_set_text: assertion 'GTK_IS_LABEL (label)' failed

(xviewer:9568): Gtk-CRITICAL **: 10:33:57.477: gtk_label_set_text: assertion 'GTK_IS_LABEL (label)' failed

(xviewer:9568): Gtk-CRITICAL **: 10:33:57.477: gtk_label_set_text: assertion 'GTK_IS_LABEL (label)' failed

(xviewer:9568): Gtk-CRITICAL **: 10:33:57.477: gtk_label_set_text: assertion 'GTK_IS_LABEL (label)' failed

(xviewer:9568): Gtk-CRITICAL **: 10:33:57.477: gtk_label_set_text: assertion 'GTK_IS_LABEL (label)' failed

(xviewer:9568): Gtk-CRITICAL **: 10:33:57.477: gtk_label_get_label: assertion 'GTK_IS_LABEL (label)' failed

(xviewer:9568): Gtk-CRITICAL **: 10:33:57.477: gtk_widget_set_tooltip_text: assertion 'GTK_IS_WIDGET (widget)' failed

(xviewer:9568): Gtk-CRITICAL **: 10:33:57.477: gtk_label_set_text: assertion 'GTK_IS_LABEL (label)' failed

(xviewer:9568): Gtk-CRITICAL **: 10:33:57.477: gtk_label_get_label: assertion 'GTK_IS_LABEL (label)' failed

(xviewer:9568): Gtk-CRITICAL **: 10:33:57.477: gtk_widget_set_tooltip_text: assertion 'GTK_IS_WIDGET (widget)' failed

(xviewer:9568): Gtk-CRITICAL **: 10:33:57.477: gtk_label_set_text: assertion 'GTK_IS_LABEL (label)' failed

(xviewer:9568): Gtk-CRITICAL **: 10:33:57.477: gtk_label_get_label: assertion 'GTK_IS_LABEL (label)' failed

(xviewer:9568): Gtk-CRITICAL **: 10:33:57.477: gtk_widget_set_tooltip_text: assertion 'GTK_IS_WIDGET (widget)' failed

(xviewer:9568): Gtk-CRITICAL **: 10:33:57.477: gtk_label_set_text: assertion 'GTK_IS_LABEL (label)' failed

(xviewer:9568): Gtk-CRITICAL **: 10:33:57.483: gtk_widget_queue_draw: assertion 'GTK_IS_WIDGET (widget)' failed

**Comment by programmer-ceds** [comment]
I can reproduce this by enabling "Edit/Preferences/Plugins/Exif Display". With this plugin not selected I don't get the errors but "File/Properties" or right-clicking on the image and selecting "Properties" gives (at least some, possibly all available - I haven't checked) EXIF data on the "Metadata" and "Details" tabs.

It could be that the plugin is no longer required (and is effectively broken).

**Comment by poldon** [comment]
I had rebooted after reporting this, and it has worked fine since. Not sure why, but I'll close this.
