### ISSUE TITLE
Please add support for WebP files [Feature Request]

### ISSUE THREAD

**Issue by Harry-W-Haines-III** [linuxmint/xviewer#142]
Please consider adding the ability to view WepP graphics files.

"WebP is an image format employing both lossy[6] and lossless compression, and supports animation and alpha transparency. Developed by Google, it is designed to create files that are smaller for the same quality, or of higher quality for the same size, than JPEG, PNG, and GIF image formats.

The WebP format was announced in September 2010, and the supporting library reached version 1.0 in April 2018. Support for the format has increased over the years, and as of May 2021 WebP was supported by 94% of the web browsers in use worldwide."

https://en.wikipedia.org/wiki/WebP

**Comment by haggen88** [comment]
related to #23 & #107

**Comment by darkshram** [comment]
Recycling my own comments: Just install webp-pixbuf-loader and you will get webp support in pix and xviewer. Packages are available in Debian, Ubuntu, Linux Mint, Fedora, etc.

Same goes for jxl, heif and avif formats. Just install jxl-pixbuf-loader, heif-pixbuf-loader and avif-pixbuf-loader packages from your distribution software repositories.
