### ISSUE TITLE
Handling invalid ppm files

### ISSUE THREAD

**Issue by TehLeo** [linuxmint/xviewer#15]
If I got a ppm file with header but no data such as: "P6\n128 128\n255\n"
It is still opened and a rgb noise is shown. I'd expect the program to show error about invalid file or at least clear pixels to black.

![test](https://cloud.githubusercontent.com/assets/14963891/18751311/d43ab0f8-80de-11e6-8994-3043a44bca25.png)

**Comment by clefebvre** [comment]
I think it uses Gdk pixbuf to open the file.. if the library says it's OK, it's OK, it just shows whatever it managed to read. I'd suggest to report this upstream in Gdk if this is important.
