### ISSUE TITLE
Request to change 1:1 mode keyboard shortcut

### ISSUE THREAD

**Issue by Intrinsic1** [linuxmint/xviewer#150]
To change to 1:1 view mode you need to hit ctrl+0. This isn't good because:
- It is hard to guess what the shortcut is, when it's a combination of characters. I pushed every button on the keyboard and mouse, and then assumed for a long time that xviewer was largely missing keyboard shortcuts when nothing happened.
- ctrl+0 is inconsistent with its opposite command, where you just push F to get the Best Fit view mode. Toggling to 1:1 view mode, and back, requires different hand positions on the keyboard, or the use of two hands for one command, and one hand for the other.

It'd be nice if the keyboard shortcut for 1:1 view mode was changed to a single key press, and to also to have that single key be physically close to the key that changes back to the Best Fit mode. Not only could you easily toggle back and forth by pushing two keys with the same hand, but if someone accidentally pushes the 1:1 (or Best Fit) key they'll likely push the keys near it trying to find its opposite. Nobody is going to push F, and then guess its opposite command is ctrl+0

You don't need to worry about new people being confused by this shortcut as xviewer resets to Best Fit mode when it's restarted, or when user changes to another image. Also, as I stated above, two opposite shortcut keys, that are side by side, are more likely to be found.

**Comment by programmer-ceds** [comment]
The '1' key has provided this functionality for some time now - it zooms 1:1 about the current cursor position (so far as this is possible). Pressing '1' again returns to best fit. ('1' would seem to be an appropriate short-cut for this!)

If you use xbindkeys (or similar) you can set the middle button of the mouse to generate a '1' and then it's even easier to zoom to 1:1 about a chosen point - even more convenient and only one hand!
