### ISSUE TITLE
Xviewer does not update displayed image after file changes.

### ISSUE THREAD

**Issue by brunobcfum** [linuxmint/xviewer#151]
```
 * Xviewer version 3.0.2
 * Distribution - Mint 20.2
```

**Issue**
Xviewer does not update displayed image after file changes.

**Steps to reproduce**
- Open image
- Change the image file (can be with Gimp for instance)

**Expected behaviour**
Image shown in Xviewer is updated with the content of the updated file

**Other information**
It worked like that in Mint 20.1 with version 2.8.3. I downgraded xviewer in Mint 20.2 to version 2.8.3 but it still does not work. Could it be related to something else on Mint 20.2? It work as expected with Eye of Gnome for example.

**Comment by programmer-ceds** [comment]
This issue can now be closed.

**Comment by brunobcfum** [comment]
Thank you!
