### ISSUE TITLE
Holding arrow key should not skip pictures.

### ISSUE THREAD

**Issue by HT-7** [linuxmint/xviewer#160]
```
Xviewer 1.6.1
Mint 18.3
```

## Issue

When I hold arrow keys to quickly browse between pictures in order to find something I am looking for, xviewer skips pictures, which makes it useless for seeking, whereas IrfanView for Windows shows each picture.

One could view each picture by pressing the arrow keys individually, but when seeking through hundreds of photos, that is highly inconvenient.

## Steps to reproduce

* Open photo in populated directory
* Hold left or right arrow key

## Expected behaviour

Each picture should be shown. No picture should be skipped.

**Comment by programmer-ceds** [comment]
You are using old versions of xviewer and Mint. I don't think that any change would be back-ported to the versions you say you are using.

How long do you think that each image should be displayed for before the program stops ignoring the keypress repeats and moves to the next/previous image?

As a work-around you could set the slideshow time to the minimum 1 second, start a slideshow and then press Esc to stop it when you see the image you want.

**Comment by programmer-ceds** [comment]
When using IrfanView on Windows how long does it take to show (say) 50 or 100 images when you hold down the left or right arrow key? Does the time for which each image is shown seem about right? Do some files take longer to display than others?
