### ISSUE TITLE
Text in SVG images not displayed correctly

### ISSUE THREAD

**Issue by tfpf** [linuxmint/xviewer#161]
```
 * Xviewer version 3.0.2
 * Distribution Linux Mint 20.2 (Uma)
```

**Issue**
Xviewer does not correctly render SVGs containing text tags if a list of coordinates is specified.

**Steps to reproduce**
Save the following text to a file, say `image.svg`.
```
<svg width="100" height="20" xmlns="http://www.w3.org/2000/svg" version="1.1">
    <rect width="100%" height="100%" fill="#EEEEEE" />
    <text x="0 33 67" y="18">Foo</text>
</svg>
```
Open it using Xviewer.

**Expected behaviour**
![A_firefox_is_correct](https://user-images.githubusercontent.com/19171016/167164375-fdac3a39-d68a-4e84-849c-f8faa51efa51.png)

**Actual Behaviour**
![B_xviewer_is_wrong](https://user-images.githubusercontent.com/19171016/167161805-fa45cb3e-d83a-430f-a4ff-497d7e48f20e.png)

**Other information**
* Firefox renders it correctly (that's how I got the first image).
* The font in the two images differs, but that is only because Firefox uses its default typeface, which is not the same as my system default typeface. The only bug seems to be the positioning of the glyphs.
* Handling lists of coordinates (as in the SVG code above) is described in section 11.2.1 of the [standard](https://www.w3.org/TR/SVG/text.html).
> If a comma- or space-separated list of _n_ \<length\>s is provided, then the values represent new absolute X (Y) coordinates for the current text position for rendering the glyphs corresponding to each of the first _n_ addressable characters within this element or any of its descendants.

**Comment by programmer-ceds** [comment]
As you say Firefox takes note of the list of x coordinates (as does Inkscape) but xviewer, pix and GIMP (V2.10.30 and V2.99.10) do not.

However, this appears to be a problem in librsvg (which both xviewer and GIMP both use). See the following fault report:

https://gitlab.gnome.org/GNOME/librsvg/-/issues/183

This issue should be closed as it isn't specifically an xviewer problem.

**Comment by tfpf** [comment]
Great point; I didn't think of comparing how other tools like Pix render it.

Closing because (as pointed out) it is a problem with the library.
