### ISSUE TITLE
Xviewer build issue

### ISSUE THREAD

**Issue by vladimir-didenko** [linuxmint/xviewer#177]
```
 * Xviewer version - 3.2.11
 * Distribution - Alt Linux Sisyphus
```

**Issue**
I couldn't build the latest xviewer version because of the following error
```
cc -Isrc/libxviewer.so.p -Isrc -I../src -Ijpegutils -I../jpegutils -I. -I.. -I/usr/include/gio-unix-2.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/gtk-3.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/atk-1.0 -I/usr/include/freetype2 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/libpeas-1.0 -I/usr/include/gobject-introspection-1.0 -I/usr/include/cinnamon-desktop -I/usr/include/xapp -I/usr/include/libexif -I/usr/include/exempi-2.0 -I/usr/include/librsvg-2.0 -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -O2 -g -DHAVE_CONFIG_H -Wno-deprecated-declarations -Wno-deprecated -Wno-declaration-after-statement -pipe -frecord-gcc-switches -Wall -g -O2 -flto=auto -fPIC -pthread -MD -MQ src/libxviewer.so.p/xviewer-window.c.o -MF src/libxviewer.so.p/xviewer-window.c.o.d -o src/libxviewer.so.p/xviewer-window.c.o -c ../src/xviewer-window.c
../src/xviewer-window.c: In function ‘xviewer_window_key_press’:
../src/xviewer-window.c:5770:36: error: ‘False’ undeclared (first use in this function)
 5770 |     static gboolean image_loaded = False;
      |                                    ^~~~~
../src/xviewer-window.c:5770:36: note: each undeclared identifier is reported only once for each function it appears in
../src/xviewer-window.c:5801:24: error: ‘True’ undeclared (first use in this function)
```

I believe this issue was introduced by the following commit - https://github.com/linuxmint/xviewer/commit/ae6a379c7f80fdcc27da492c1f63ec2b4addc571 

Replacing True by TRUE and False by FALSE resolves issue for me.

**Comment by programmer-ceds** [comment]
Mea culpa - although it compiled fine for me and for @clefebvre . I will submit a PR to change all instances of True to TRUE and False to FALSE but first a question - did you also edit the occurrence of False in the call of XGetWindowProperty () around line 432 of xviewer-window.c (False to FALSE)?

**Comment by vladimir-didenko** [comment]
> did you also edit the occurrence of False in the call of XGetWindowProperty () around line 432 of xviewer-window.c (False to FALSE)?

Yes, I replaced all occurrences. Could create PR myself if you are OK.

**Comment by programmer-ceds** [comment]
@vladimir-didenko I'll assume that you are going to create the PR unless you let me know otherwise, when I will do it.

Many thanks.

**Comment by vladimir-didenko** [comment]
@programmer-ceds  Done - https://github.com/linuxmint/xviewer/pull/178
