### ISSUE TITLE
Error in build

### ISSUE THREAD

**Issue by AshwinKumar-1381** [linuxmint/xviewer#180]
```
 * Xviewer version 3.2.12-3
 * Distribution - (Arch Linux - Endeavour OS - Cinnamon version 5.6.8)
```

**Issue**
I tried to install xviewer using `yay`. 

But the build process using `ninja` stopped with the following error:

`ImportError: /usr/lib/gobject-introspection/giscanner/_giscanner.cpython-310-x86_64-linux-gnu.so: undefined symbol: g_string_free_and_steal
`

![error](https://user-images.githubusercontent.com/64678262/229278290-a228ad07-d008-43c4-88d5-fd1f44dea437.png)

**Comment by leigh123linux** [comment]
Archlinux giscanner is broken
