### ISSUE TITLE
disable double click behavior on toolbar buttons

### ISSUE THREAD

**Issue by saiballo** [linuxmint/xviewer#26]
Hi,

Is it possible to disable "double click" behavior when I click on toolbar buttons?

For example when I slide some photos with the right arrow, It opens next photo in large screen...

thanks

**Comment by chuinul** [comment]
I experienced the same behavior. I suppose this is a bug more than a feature ;-)

**Comment by JosephMcc** [comment]
Ok, this was driving me nuts. Submitted a PR to limit it to only working over the actual image.
