### ISSUE TITLE
Transparent 1px borders

### ISSUE THREAD

**Issue by Yanpas** [linuxmint/xviewer#3]
I've met the same in mate system monitor. Maybe it is gtk3 bug?
![_2016-06-10_22-48-44](https://cloud.githubusercontent.com/assets/7345761/15976791/9b9ea92a-2f5d-11e6-8fc9-5f6010eece96.png)

**Comment by JosephMcc** [comment]
Are you talking about the dashed lines?

**Comment by Yanpas** [comment]
Yes, dashed line near document borders

**Comment by JosephMcc** [comment]
They are indicators that there is more content in those directions inside of scrolled windows. They were in tandem with the new overlay scrollbars in 3.18. That way when the scrollbars aren't visible you know there is more hidden content.

**Comment by Yanpas** [comment]
IMHO they make impression like there is something wrong with app. I don't know whether they should stay in Mint-Y or not.
