### ISSUE TITLE
Permanent preference setting for "Are you sure you want to move to trash?"

### ISSUE THREAD

**Issue by nick-s-b** [linuxmint/xviewer#35]
Xviewer is my fav viewer by far but one of the things that annoys me the most is that it remembers my preference to move things to trash on a per session level only. Is there some hidden preference that would allow me to get rid of that modal dialog box forever so I can just hit Del and move things to trash? If not, can we make that feature a request?

Thanks!

**Comment by nick-s-b** [comment]
@stry-onave Give `qimgv` a try. I've been using it for years now. It's by far my fav image viewer now. You can completely customize keyboard shortcuts (and everything else for that matter).

**Comment by Benjamin-Loison** [comment]
@nick-s-b Can you re-open this issue or do you prefer that I open another issue referring to this one?
