### ISSUE TITLE
Selecting option/radio buttons does not work correctly

### ISSUE THREAD

**Issue by graue70** [linuxmint/xviewer#37]
## Steps to reproduce
1. Create an odt document with Libre Writer.
1. Add option/radio buttons and give all of them the same name.
1. Export the document to pdf, enabling form elements. This [Test.pdf](https://github.com/linuxmint/xviewer/files/1066599/Test.pdf) was created just like that.
1. Open the pdf in xviewer.
1. Click on one of the option buttons.
1. Click on another one of the option buttons.

## Expected behavior
Once the second option button is clicked, the previously selected option button should automatically be deselected.

## Actual behavior
After selecting the second option button, both the previously selected and the newly selected button are now selected. It is impossible to deselect a once selected button.

## Additional info
When I open the same pdf file with Foxit Reader, it works as expected.

Linux Mint 18.1 Cinnamon 64 bit
xviewer 1.2.2
LibreOffice 5.1.6.2

**Comment by JosephMcc** [comment]
I can confirm this with Xreader 1.4.

**Comment by JosephMcc** [comment]
It seems we both got confused. This is on the wrong repo. It needs to be moved here: https://github.com/linuxmint/xreader/issues

**Comment by graue70** [comment]
You are right.

Do you want me to open a ticket there?

**Comment by JosephMcc** [comment]
Yes, if you could. So we don't lose track of it.
