### ISSUE TITLE
Fullscreen: pause-play button icon does not update (misleading)

### ISSUE THREAD

**Issue by cmrdt** [linuxmint/xviewer#38]
when in slideshow, the button is 
**always** ⏸ instead of ▶️

maybe use switch-slider instead 
(switch-to since it's ambiguous with current-status)

![play-pause viewer](https://user-images.githubusercontent.com/24411108/27343478-06af1c98-55b1-11e7-8794-727a10b4a177.png)

Xviewer 1.2.2

**Comment by JosephMcc** [comment]
I can confirm this.
