### ISSUE TITLE
Re-add slideshow button on toolbar [feature request]

### ISSUE THREAD

**Issue by pirate486743186** [linuxmint/xviewer#43]
The slideshow button was removed from the toolbar. I think it should be added back.

Slideshow is a frequently enough used functionality
That i think should have it's button on the toolbar.
If the concern is to reduce clutter on the toolbar.
Maybe it's the rotate buttons that should go...

**Comment by programmer-ceds** [comment]
In V2.6.2 there is a slide-show button in the toolbar. This issue can therefore be closed.
