### ISSUE TITLE
Xviewer cannot display this jpeg image

### ISSUE THREAD

**Issue by nick-s-b** [linuxmint/xviewer#44]
```
 * Xviewer version: 1.4.3
 * Distribution - Arch Linux
```

**Issue**
Xviewer fails to display this image. Complains about "Unsupported number of color components (1)". I've encountered this issue dozens of times before. 

![https://i.imgur.com/NdXxW3t.jpg](https://i.imgur.com/NdXxW3t.jpg)

**Steps to reproduce**
Save the image, try to open it.

**Expected behaviour**
I'd expect to see it.

**Other information**
This image opens fine if pretty much every other viewer I've tried: feh, sxiv, Pix, GIMP etc. GNOME Image Viewer also fails to display it.

EDIT: This seems to be this bug: https://bugzilla.gnome.org/show_bug.cgi?id=785171
Will a fix of this bug be propagated to Xviewer automatically through GDK-pixbuf update?

**Comment by programmer-ceds** [comment]
xviewer 2.4.3
Linux Mint 19.1 Cinnamon

@nick-s-b 
I've just downloaded this image and it opens without a problem. If you're still around does it still fail for you?

**Comment by nick-s-b** [comment]
@programmer-ceds yep, it opens fine now! I'm happy that the bug was fixed. Thanks.
