### ISSUE TITLE
[Feature Request] Remember the window size and state after closed

### ISSUE THREAD

**Issue by s101d1** [linuxmint/xviewer#47]
```
 * Xviewer version: 1.2.2
 * Distribution: Mint 18.1
```

Could you make the app to remember the window size and states (i.e. maximized) after closed ?

Currently the app always resize the app's window to the image size. 

I prefer if I maximize the window and close the app, the next time I launch the app, the window should be maximized.

**Comment by programmer-ceds** [comment]
Pull request #95 which has been merged addresses both the remembering of whether or not the image window was maximized when xviewer was last closed. I think that this issue could now be closed.
