### ISSUE TITLE
Please append program name to tar archive.

### ISSUE THREAD

**Issue by Jeroen0494** [linuxmint/xviewer#5]
Hi there,

Would you be so kind as to append the name of the program to the zip and tar archive of the releases? This would improve support for a lot of AUR helpers on Arch Linux and make it much easier to distinguish the packages in my src folder. Right now I run into problem with my AUR helper thinking the package of xviewer has already been downloaded, while it is actually that of xreader since they have the same version number. This causes the checksum verification to fail and consequently the build to fail.

Please do the same for all other xapp programs (xreader and such).

Thank you,
Jeroen

**Comment by ion201** [comment]
(xapps aur maintainer here). I'm not sure if this is the best solution to this problem. I think you could also argue that this is the fault of the aur helper developer for allowing naming conflicts to silently mess up a build. From this perspective, it makes more sense to change the helper rather than to change the standard release names for projects here.

**Comment by Jeroen0494** [comment]
Many distribution use a central (single) folder to store all source files. My AUR helper simply uses this existing functionality provided by Arch Linux. By not including the name of the software for the source it becomes impossible to use a single source folder.

**Comment by ion201** [comment]
"Many distribution use a central (single) folder to store all source files."

Arch Linux doesn't have such a thing. Without using the abs package, you won't find the source for your packages anywhere in the filesystem. And even if it did have such a thing, you shouldn't be mixing sources from repositories and AUR packages.

 The AUR helper's core purpose is to 1. Download PKGBUILD. 2. Run PKGBUILD. Anything beyond that (eg, caching source packages) is extra functionality. If the extra functionality doesn't work but the base PKGBUILD does, that's a helper bug. In this specific case, if the helper wants to cache packages, it should organize it's cache in a way which does not depend on the filename.

**Comment by Jeroen0494** [comment]
Arch Linux does have such a thing, the ABS. You specify a the folder for all the source files in your make.conf. This is no different from the AUR helper. You may be right by saying that this isn't the problem of the linuxmint project, but is definately is not the problem of the AUR helper.

**Comment by ion201** [comment]
You're right -- I misunderstood your original point in my response. My argument should have included why I don't like abs for aur packages but that's an issue for another discussion. 
On Jun 12, 2016 10:28 AM, Jeroen <notifications@github.com> wrote:Arch Linux does have such a thing, the ABS. You specify a the folder for all the source files in your make.conf. This is no different from the AUR helper. You may be right by saying that this isn't the problem of the linuxmint project, but is definately is not the problem of the AUR helper.

**Comment by clefebvre** [comment]
Hi Jeroen,

I'm sorry, these release/tag archives are generated by github automatically. I'm not aware of any configuration we could change in that regard.

That said, I've very limited knowledge about how your script/infrastructure downloads the archive, but I'm sure there's a way you might get the filename you want. For instance, if you're using wget, you could use the -O flag to specify the filename. Alternatively you could follow up the download with a filename rename, either with mv or rename and a regexp? Another way you can use is using git itself to download the source... i.e. "git clone" to clone the repo locally, followed by "git checkout tagname" to place yourself at the wanted release tag. You can then zip or tar things the way you want.

**Comment by Jeroen0494** [comment]
Followup: Arch Linux provides a way to rename the packages when downloaded like so:
source=("${_pkgname}"::git+https://github.com/linuxmint/mint-y-icons.git)

https://wiki.archlinux.org/index.php/PKGBUILD#source
