### ISSUE TITLE
All extensions are not available and there is no doc about how to add them

### ISSUE THREAD

**Issue by juliencarnot** [linuxmint/xviewer#52]
```
 * Xviewer version 1.6.1
 * Distribution - Mint 18.2
```

**Issue**
Extensions listed in https://github.com/linuxmint/pix/tree/master/extensions such as map_view or flicker are not available in edit/preferences/extensions lists.

The "more extensions" button [points to the repo](https://github.com/linuxmint/pix).

The [help page](https://github.com/linuxmint/pix/blob/master/help/C/extensions.page) does not explain how to add new extensions or if all extensions present in the repo should be available.

**Steps to reproduce**
Look for map_view plugin in the edit/preferences/extensions screens

**Expected behaviour**
Extension should be available, or the way to add it to the list should be documented.

**Other information**

**Comment by breversa** [comment]
Any reason to close this issue ?

**Comment by juliencarnot** [comment]
It seems it was regarding Pix rather than Xviewer: https://github.com/linuxmint/pix/issues/45
xviewer doesn't have a "more extensions" button
