### ISSUE TITLE
Request APNG format support

### ISSUE THREAD

**Issue by Snarkly** [linuxmint/xviewer#53]
Please fix xviewer so it supports animated png formats too.

**Comment by Modanung** [comment]
Indeed, that would be nice.
![Chaosphere](https://upload.wikimedia.org/wikipedia/commons/8/88/AnimatedChaosphere.png)
Support for [animated SVGs](65) would also be awesome.
![Moire](https://luckeyproductions.nl/images/moire.svg)

**Comment by leigh123linux** [comment]
Request it for gdk-pixbuf

https://gitlab.gnome.org/GNOME/gdk-pixbuf/issues
