### ISSUE TITLE
Install on ubuntu

### ISSUE THREAD

**Issue by Greentash** [linuxmint/xviewer#58]
```
 * Xviewer version (xviewer --version)
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
```
I already saw LinuxMint evidently. what i want? I would like to install this awesome tool on ubuntu 16.04 X64
**Issue**
./configure: line 2138: syntax error near unexpected token `1.11'
./configure: line 2138: `AM_INIT_AUTOMAKE(1.11 foreign no-dist-gzip dist-xz)'

**Steps to reproduce**
After download&unzip, 
$ cd /xviewer-master.mint19
$ sudo ./configure && make && make install

**Comment by leigh123linux** [comment]
Install the deps listed here

https://github.com/linuxmint/xviewer/blob/master/debian/control#L7

use
```
./autogen.sh
./configure
make
sudo make install
```

Also why use sudo to configure and make?, we don't support this bad practice.

**Comment by JosephMcc** [comment]
On ubuntu just build the debs. Clone the repo and run `dpkg-buildpackage`. Then install the resulting .deb files

**Comment by unihernandez22** [comment]
I have the same problem on Arch

**Comment by leigh123linux** [comment]
> I have the same problem on Arch

Try using the arch package

https://aur.archlinux.org/packages/xviewer/
