### ISSUE TITLE
Mousewheel Zoom Inconsistent with other apps

### ISSUE THREAD

**Issue by acornforth** [linuxmint/xviewer#59]
```
 * Xviewer version (1.6.1)
 * Distribution - (Mint 18.3 x64 Cinnamon)
```

**Issue**
mouse-wheel acts as zoom without any modifiers, this is inconsistent with the majority of other apps where ctrl+mouse-wheel is zoom, mouse-wheel-only is vertical scroll, and shift+mouse-wheel is horizontal scroll.

**Steps to reproduce**
use mousewheel in app

**Expected behaviour**
I would like to see the following either as default behaviour, or as an optional configuration:
mouse-wheel = v-scroll
shift+mouse-wheel = h-scroll
ctrl+mouse-wheel = zoom

**Other information**
Lets have sensible defaults here, consistent with other apps in the xapps suite, with preferences to configure to users taste.
These lightweight xapps are great, fast loading productivity tools, but with out shortcut preferences and with inconsostent shortcuts, it have have a significant impact on workflow, having to remember, "oh wait, this app is different and that 'goto' shortcut i always use doesn't work here!"

**Comment by acornforth** [comment]
Same applies to pix, i'm really not a fan of ctrl+mouse-wheel navigating between images in folder, this is very unintuitive behaviour

**Comment by nick-s-b** [comment]
This behavior is actually desirable in image viewers. All the good ones  do it. Behavior + modifier is what the DEs do.

**Comment by progzy** [comment]
+1 ; thank you.

**Comment by acornforth** [comment]
> This behavior is actually desirable in image viewers. All the good ones do it. Behavior + modifier is what the DEs do.

you have a point, many popular image viewers/editors do ship with that as the default option.
but _all the good ones_ can be configured differently if the user has a different workflow or preference.
In fact, as far as I know,  All the most popular image viewing/manipulation programs - where they belong to a suite of apps - have at the very least made their keyboard shortcuts consistent across the suite... 
this is all i am asking for...
i don't want to inconvenience anyone who likes it this way, which is why i propose it should be an option.
Ultimately it should be the users choice.

**Comment by mscheper** [comment]
It seems some people like the current behaviour, while others (including myself) find it counterintuitive. This is a pretty straightforward thing to provide a Preferences option for. (I know some PMs and UX designers think options overwhelm users and should therefore be avoided, but please don't let's put the needs of hypothetical, easily scared users above actual users who have taken the time to comment above… especially for a Linux app.)

**Comment by programmer-ceds** [comment]
With the merging of PR #111 I believe that this issue can be closed.
