### ISSUE TITLE
... Retracted ...

### ISSUE THREAD

**Issue by MvGulik** [linuxmint/xviewer#64]
Never mind. Not going to wast time on a project that's has no heartbeat.

**Comment by JosephMcc** [comment]
Not sure I understand why. Because you weren't answered quickly enough? It was the weekend and we are in the middle of a new release so other things are getting the focus at the moment.

**Comment by MvGulik** [comment]
... I doubt reality is that blank and white. But if you like, sure.
Besides ... can't really deny it did not play a part, now can I.

Case resolved, I think.

**Comment by MvGulik** [comment]
NTS: Sunday, May 17, 2020.

```
[All - Bug tagged - (opened: 2020 - 2019 - 2018 - 2017 - 2016)]
Open: 49 - 24 - (2 - 7 - 8 - 6 - 1)
Closed: 28 - 5 - (0 - 0 - 0 - 2 - 3)
```
