### ISSUE TITLE
"Suspension not allowed here" error

### ISSUE THREAD

**Issue by Martina-Neumayer** [linuxmint/xviewer#67]
```
 * Xviewer version 1.6.1
 * Distribution - Mint 18.3 Mate x64

**Issue**

As on the attached screenshot

![screenshot](https://user-images.githubusercontent.com/13028529/42720612-7d05d9d0-872a-11e8-939c-7a7a4a6569fd.png)

**Steps to reproduce**
Download or take some existing jpg picture.
Open it with Gimp, do what ever you want with this pic.
Save it with the default settings as they are ootb.
Now try to open the pic with the default mint viewer app -> Xviewer.


**Expected behaviour**
eeemmm..
I expect an working as it should be application.
Yes.. an working app, not a Santa Claus.
And yes.. I am sure.

**Other information**
I am pissed off. Really pissed off..
Is now 4:04 AM and I can not finish my work due to some crappy not working app!
Damn!
Sorry.. but I must say this.
From release to release.. Mint goes more and more in the a**!
This was one of the nice looking and working distro I ever used.. some time ago.
Now is an bunch of not working, randomly crashing and throwing with the strange bugs thing.
As an long time mint user (yeap I am with this distro from the beginning) I am very disappointed with the level of lack of quality which is currently now.

**Comment by JosephMcc** [comment]
Ok. I know you feel strongly about this but that isn't the way to get help get people motivated to fix things. 

I'm running Xviewer 1.8.1 and couldn't reproduce this issue with random .jpg I used. You need to be a bit more specific about how you saved out of Gimp though. You said save it with default setting but there are many ways to save out of it. Did you save it as a .xcf? Overwrite the existing .jpg? As far as I remember we never supported opening .xcf.

**Comment by Martina-Neumayer** [comment]
@JosephMcc I don't motivate no one to nothing. I just do a bugreport. I am not some motivation person etc.
And to be honest, what I felt was hmm.. faaaar away from the "strongly" word.
This was a "sarcasm at the morning mode" mixed with a not finished work and lot's of coffe.

Okay.. Back to the main topic..
Save in the meaning I just hit ctrl+e and exported thie pic as normal jpg. This is an normal jpg file.
And those are the export settings:
![screenshot_1](https://user-images.githubusercontent.com/13028529/42721590-b4a8edec-873d-11e8-8437-76a5fe035845.png)

**Comment by JosephMcc** [comment]
There are some differences here. I'm on Mint19 so have a different xviewer version and also different versions of the libraries it uses. The Gimp export settings are also a bit different. I can't reproduce you're issue here. It seems to work fine.

Do you still have the issue if you use set the gimp export settings to the defaults?

**Comment by leigh123linux** [comment]
@JosephMcc  That excuse for a user was lucky you got here first, after reading his childish rant I was just going to close it.
I guess I will just unsubscribe from the worthless rude users issue instead.

**Comment by Martina-Neumayer** [comment]
Issue closed.
I (and lot's of users too) don't simply have a time for some bs like this abowe and such pitty crap like giving the people an unstable and very buggy software and telling them that is a stable one. 
Mint is now removed from the machines entierly thanx to You dear "sir developer".
So.. Do as you want.
I don't care anymore.
Cheers.

**Comment by JosephMcc** [comment]
Messages were deleted here by the OP who was rather less than well mannered. Just locking it because nothing else needs to be said.
