### ISSUE TITLE
Error message "BMP image has bogus header data"

### ISSUE THREAD

**Issue by MGarvinNYC** [linuxmint/xviewer#69]
```
 * Xviewer version (xviewer --version)     v 1.2.1
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)   Mint 17.2
```

**Issue**

.bmp files not recognized.  Error message "BMP image has bogus header data"
Is this due to one of the libraries used in Xviewer?  If so, can the bug be addressed?

**Steps to reproduce**

I've seen this on BMP files, but have not noticed any problems with other file formats.
Again, the wording of the error message seems to come up in web searches, but for
different programs. Possibly a known bug in a third party library.

**Expected behaviour**

**Other information**

**Comment by programmer-ceds** [comment]
Was the BMP file that is causing the error message created in GIMP?

There would appear to be a bug in GIMP (at least in V2.10.22) in saving 24-bit BMP files with colour-space information. There doesn't appear to be a problem with 16 bits (R5G6B5, A1R5G5B5 or X1R5G5B5) or 32 bits (A8R8G8B8 or X8R8G8B8) with colour-space information or in saving 24 bit files without colour-space information but even GIMP won't open 24-bit BMP files that it saved with colour-space information!

The problem appears to be with the value of the Compression field in the BMP V5 header for these files - this is set to 3 for all of the BMP variants that GIMP saves if the colour-space is included - the Microsoft specification for the V5 header says that this is valid for 16 and 32-bit files.

If you have a file that is like this (byte at offset 0x0E set to 0x7C and the byte at offset 0x1E set to 0x03) then (working on a COPY of the file) edit the byte at offset 0x1E from 0x03 to 0x00. It will then open successfully with GIMP, xviewer and pix whereas before none of them would open it.

Off now to double check that there isn't already a bug report for this with GIMP and then file a report.

If your file wasn't created with GIMP perhaps you could post it and I'll look at it.

**Comment by programmer-ceds** [comment]
I have posted PR #125 which addresses the issue of 24-bit BMP files with colour space information included. At least for files of this format generated by GIMP the bug lies in GIMP. The PR is a work-around that changes the compression type from uncompressed with bit fields (BI_BITFIELDS) to uncompressed without bit fields (BI_RGB) - presumably Microsoft assumed that 24 bits per pixel would only ever be interpreted as 8 bits for each of R, G and B.

**Comment by programmer-ceds** [comment]
Following the merging of PR 125 I think that this issue can now be closed.
