### ISSUE TITLE
No resampling on zoom

### ISSUE THREAD

**Issue by scytho** [linuxmint/xviewer#8]
Hi,
I just took a look at Mint 18. Being based on it, Xviewer has the same bug as Eye of Mate: https://github.com/mate-desktop/eom/issues/96

It was confirmed over there, but it seems the developers aren’t much interessed in it … The annoying thing is, it’s an old bug, it was gone for a while, and is back since Mint 17.2 (I don’t know the version number of EOM in Mint 17.2).

**Comment by xenopeek** [comment]
Here are the eom versions of all current Linux Mint versions:
- Linux Mint 13 - 1.6.1 (earlier it was 1.2.0)
- Linux Mint 17 - 1.8.0
- Linux Mint 17.1 - 1.8.1
- Linux Mint 17.2 - 1.12.0 (earlier it was 1.10.3)
- Linux Mint 17.3 - 1.12.2
- Linux Mint 18 - 1.14.1
- LMDE 2 - 1.14.1
You can find the packages on http://packages.linuxmint.com/. 

I don't know what version xviewer is based on. From the linked issue I tried with the image https://cloud.githubusercontent.com/assets/13711754/9154774/4532ba44-3ea0-11e5-98d6-c329f3a8853d.png on Linux Mint 13 with eom 1.2.0 and zoomed to 25%. Doing the same on Linux Mint 18 with xviewer indeed gives a much grainier, less sharp, and less smooth image.
