### ISSUE TITLE
I can't compile Xviewer 2.0.2

### ISSUE THREAD

**Issue by Solus32** [linuxmint/xviewer#82]
Xviewer version 2.0.2
Debian 10 Buster

I read README from https://github.com/linuxmint/xviewer  ---> Doesn't tell you what dependencies it needs, how to install.

Yesterday i install from source Xed 2.0.2 , Xreader 2.0.2, these programs installed just fine, and runs excellent on Debian 10 Buster. The problem lacks on the installation of Xviewer.

First i read INSTALL , y try everything, doesn't work

I can't compile Xviewer 2.0.2 from source i try these:

./configure

And appears this message in terminal using ./configure

bash: ./configure: No existe el fichero o el directorio
bash: ./configure: Doesn't exist the file or the archive

So i try

./autogen     ---> Doesn't work

I need help. To Compile and to install.
Thank you

**Comment by leigh123linux** [comment]
You will need to run autoreconf first
```
autoreconf -fiv
```
