### ISSUE TITLE
deficient saturation

### ISSUE THREAD

**Issue by gridelin** [linuxmint/xviewer#9]
Xviewer shows images, at least png and jpg, with less saturation than other image viewers like pix or gthumb. I'm on Linux Mint 18 Cinnamon 64-bit.

Here's a screenshot with xviewer on the left and pix on the right:

![screenshot xviewer vs pix](https://cloud.githubusercontent.com/assets/18901305/17632196/566f80a4-60c7-11e6-8794-f25e984a8a76.png)

**Comment by xenopeek** [comment]
Can you link the source image or upload it?

**Comment by gridelin** [comment]
Here's the link to the image: https://commons.wikimedia.org/wiki/File:Rosa_rubiginosa_1.jpg

**Comment by xenopeek** [comment]
I can see the difference in your screenshot but with the image itself unfortunately I can't reproduce this. xviewer, pix, and Firefox all show the same image for me without such saturation differences.

**Comment by gridelin** [comment]
Thanks for trying it out. I tested it with a new user account but the problem is the same so it appears to be system-wide. Here's the output from `inxi -Gxx`:

`Graphics:  Card: Advanced Micro Devices [AMD/ATI] Thames [Radeon HD 7550M/7570M/7650M]`
`bus-ID: 01:00.0 chip-ID: 1002:6841`
`Display Server: X.Org 1.18.3 drivers: ati,radeon (unloaded: fbdev,vesa)`
`Resolution: 1920x1080@59.98hz, 1024x768@60.00hz`
`GLX Renderer: Gallium 0.4 on AMD TURKS (DRM 2.43.0, LLVM 3.8.0)`
`GLX Version: 3.0 Mesa 11.2.0 Direct Rendering: Yes`

**Comment by clefebvre** [comment]
I can't reproduce this issue.

**Comment by gridelin** [comment]
OK, thanks for trying to reproduce it.
