### ISSUE TITLE
[Feature Request] HEIF/HEIC support

### ISSUE THREAD

**Issue by carsonip** [linuxmint/xviewer#91]
Not sure if this is the right place to request a file format support. Since [HEIF/HEIC](https://en.wikipedia.org/wiki/High_Efficiency_Image_File_Format) is getting more popular as Android and iOS phone cameras are starting to save images in the format, I'm wondering if Xviewer is going to support it. It seems that newer versions of GIMP is shipping with HEIF/HEIC support. Thanks!

**Comment by leigh123linux** [comment]
It shouldn't be that hard to add as it has it's own gdk-pixbuf loader

https://koji.rpmfusion.org/koji/fileinfo?rpmID=563757&filename=/usr/lib64/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-heif.so

**Comment by carsonip** [comment]
It actually sounds fun to work on this, but I don't have any experience in gtk. If it will take you 15 minutes to support the file format, I'd rather not spend a few days on this. If you don't mind guiding me and reviewing my code, I am happy to add this feature to the project.

**Comment by leigh123linux** [comment]
It works ok without any changes after installing libheif gdk-pixbuf loader.

![Screenshot from 2020-03-19 16-22-39](https://user-images.githubusercontent.com/1299302/77089629-f833ad00-69fd-11ea-82bd-401a3316ac9a.png)

**Comment by carsonip** [comment]
Sorry if this sounds stupid but how do I install that?

**Comment by leigh123linux** [comment]
Ubuntu distros need heif-gdk-pixbuf

https://launchpad.net/ubuntu/eoan/+package/heif-gdk-pixbuf

**Comment by carsonip** [comment]
I see. I'm using Linux Mint 19.3 here. Guess there's no easy way for me. Thanks anyway!

**Comment by dsvf** [comment]
This used to work for me (LM 20.1) after installing heif-gdk-pixbuf, heif-thumbnailer and libheif1. Nemo also shows the heic thumbnails. However, when I tried to open a .heic-file today, Xviewer (2.8.3) simply says "Could not load image 'foo.heic'. Unrecognized image file format"

**Comment by tmanok** [comment]
> 

For Linux Cinnamon (20.3) I only needed to `sudo apt install heif-gdk-pixbuf` to get nemo to preview heic photos create by an iOS device. Cheers,

Tmanok

**Comment by forkthat** [comment]
Hello guys! 
Even now, I still can't open HEIC files even with `heif-gdk-pixbuf` installed.

**Comment by firewiremb** [comment]
Using Linux Mint 22.3. heif-gdk-pixbuf is installed and it does not work. Poor performance after 6 years.
