### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by dodona2** [linuxmint/xviewer#92]
```
 * Xviewer version (xviewer --version)
git 
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
```
Fedora 31

**Issue**
configure.ac:9: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:28: error: possibly undefined macro: AM_MAINTAINER_MODE
configure.ac:39: error: possibly undefined macro: AM_PROG_CC_C_O
configure.ac:69: error: possibly undefined macro: AM_GLIB_GNU_GETTEXT
configure.ac:160: error: possibly undefined macro: AM_CONDITIONAL
./configure: line 2122: syntax error near unexpected token `1.11'
./configure: line 2122: `AM_INIT_AUTOMAKE(1.11 foreign no-dist-gzip dist-xz)'
configure.ac:9: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:28: error: possibly undefined macro: AM_MAINTAINER_MODE
configure.ac:39: error: possibly undefined macro: AM_PROG_CC_C_O
configure.ac:69: error: possibly undefined macro: AM_GLIB_GNU_GETTEXT
configure.ac:160: error: possibly undefined macro: AM_CONDITIONAL
./configure: line 2122: syntax error near unexpected token `1.11'
./configure: line 2122: `AM_INIT_AUTOMAKE(1.11 foreign no-dist-gzip dist-xz)'

**Steps to reproduce**
automake
./configure

**Expected behaviour**
no errors

**Other information**

**Comment by leigh123linux** [comment]
Compiles fine here on f31

```
NOCONFIGURE=1 /usr/bin//gnome-autogen.sh
./configure
make
```

**Comment by dodona2** [comment]
I had to install /usr/bin//gnome-autogen.sh as No such file or directory

**autogen**:
configure.ac:9: installing './missing'
src/Makefile.am:208: error: HAVE_INTROSPECTION does not appear in AM_CONDITIONAL
autoreconf: automake failed with exit status: 1

** ./configure**
checking for itstool... itstool
checking for xmllint... xmllint
checking for itstool... itstool
checking for xmllint... xmllint
**./configure: line 12271: syntax error near unexpected token `0.9.3'
./configure: line 12271: `GOBJECT_INTROSPECTION_CHECK(0.9.3)'**
checking for itstool... itstool
checking for xmllint... xmllint

**Comment by leigh123linux** [comment]
You need to install the build deps, the error is happening because gobject-introspection-devel isn't installed.

**Comment by dodona2** [comment]
guess we are very close. Got that after invoking:
(xviewer:142800): GLib-GIO-ERROR **: 09:59:27.619: Settings schema 'org.x.viewer.plugins' is not installed

**dependency list:**
dnf install gnome-common # xviewer
dnf install gobject-introspection-devel # xviewer
dnf install cinnamon-desktop-devel # xviewer
dnf install libpeas-devel # xviewer

**Comment by leigh123linux** [comment]
Did you remember to set the prefix?

```
./configure --prefix=/usr
```

you need to run this for schemas

```
glib-compile-schemas /usr/share/glib-2.0/schemas
```

or if you installed to local

```
glib-compile-schemas /usr/local/share/glib-2.0/schemas
```

**Comment by dodona2** [comment]
- first of all thanks a lot 4 the support!
- the prefix is set to /opt/xviewer
- sorry, but **glib-compile-schemas doesn't change anything**

**Comment by dodona2** [comment]
- contents of  /opt/xviewer/share/glib-2.0/schemas/
**gschemas.compiled  org.x.viewer.enums.xml  org.x.viewer.gschema.xml**

**Comment by dodona2** [comment]
got it finally. However ./configure cannot offer a --prefix when prefix must be either /usr or /usr/local:

ln -s /opt/xviewer/share/glib-2.0/schemas/*xml /usr/share/glib-2.0/schemas/
glib-compile-schemas /usr/share/glib-2.0/schemas/
ln -s /opt/xviewer/share/applications/xviewer.desktop /usr/local/share/applications/
